# Generated by Django 6.0.1 on 2026-01-22 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='pub_date',
        ),
        migrations.RemoveField(
            model_name='question',
            name='question_text',
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
    ]
